name: board_app
description: "Board67 App that communicates with ESP32 controller to light routes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider:
  flutter_blue_plus: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"


flutter_icons:
  image_path: "icon/icon.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/holds/
    - assets/boards/
